version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DBNAME}

  api:
    build: .
    restart: always
    environment:
      - KNOX_AUTH_HOST=http://auth:8000/auth/accounts/
      - DB_DBNAME=${DB_DBNAME}
      - PORT=${API_PORT}
      - DEBUG=${DEBUG}
      - DB_HOST=db
    volumes:
      - ./:/app/
    depends_on:
      - db

  auth:
    image: dmitriyvasil1986/knox_auth:latest
    restart: always
    environment:
      - DB_DBNAME=${DB_DBNAME}
      - PORT=${AUTH_PORT}
      - DEBUG=${DEBUG}
      - DB_HOST=db
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
