version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${DB}
  api:
    build: .
    restart: always
    environment:
      - DB_DBNAME=${DB}
      - DEBUG=True
      - DB_HOST=db
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
