# Generated by Django 3.1.7 on 2021-06-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
